name: sumador
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  geolocator: ^11.0.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  syncfusion_flutter_calendar: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:

  - assets/bluey/
