// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfrUeZF45W7AEW7XCY2vJRjjWTlXTWBRo',
    appId: '1:533971542263:web:1ce98f90b6f44e5ee0f3f2',
    messagingSenderId: '533971542263',
    projectId: 'pm-2857',
    authDomain: 'pm-2857.firebaseapp.com',
    storageBucket: 'pm-2857.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpBChhnZ0_nThbkuFrmaKZzgXwya4SugM',
    appId: '1:533971542263:android:8f045871f406d2b6e0f3f2',
    messagingSenderId: '533971542263',
    projectId: 'pm-2857',
    storageBucket: 'pm-2857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOcjntMsWA0QgiumY_1G-TyOYzJDK4oo',
    appId: '1:533971542263:ios:332ff1cbf30cbd3ce0f3f2',
    messagingSenderId: '533971542263',
    projectId: 'pm-2857',
    storageBucket: 'pm-2857.appspot.com',
    iosBundleId: 'com.example.sumador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOcjntMsWA0QgiumY_1G-TyOYzJDK4oo',
    appId: '1:533971542263:ios:2fec903d9706c740e0f3f2',
    messagingSenderId: '533971542263',
    projectId: 'pm-2857',
    storageBucket: 'pm-2857.appspot.com',
    iosBundleId: 'com.example.sumador.RunnerTests',
  );
}
